name = "TreeKnit"
uuid = "03f602be-98a1-4bb2-9504-fbd3406624a7"
authors = ["PierreBarrat <p.barrat@live.fr>"]
version = "0.1.0"

[deps]
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
TreeTools = "62f0eae3-8c0e-4032-a621-7756092209e5"

[compat]
julia = "1.6"